[tool.black]
line-length = 119
exclude = '''
(
    migrations
    | .mypy_cache
    | .pytest_cache
    | .ruff_cache
    | .venv
    | target
)
'''

[tool.ruff]
line-length = 119

select = ["F", "E", "W", "I"]

exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".pytest_cache",
    ".venv",
    "dist",
    "target",
]

[tool.taskipy.tasks]
fmt_black = "black ."
fmt_ruff = "ruff . --fix"
fmt_rust = "cargo fmt"
fmt = "task fmt_black & task fmt_ruff &task fmt_rust"

lint = "ruff ."

dev = "maturin dev -E dev,doc --manifest-path=ffmpegwithpy-rust/Cargo.toml"

build = "maturin build --release -o dist --manifest-path=ffmpegwithpy-rust/Cargo.toml"

doc = "cargo doc -p ffmpegwithpy-core"
