[tool.black]
line-length = 119
exclude = '''
(
    migrations
    | .mypy_cache
    | .pytest_cache
    | .ruff_cache
    | .venv
    | target
)
'''

[tool.isort]
profile = "black"
line_length = 119

[tool.ruff]
target-version = "py37"

line-length = 119

select = [
    "F",  # pyflakes
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    # "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "N",  # pep8-naming
]

exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".pytest_cache",
    ".venv",
    "dist",
    "target",
]

[tool.taskipy.tasks]
fmt_black = "black ."
fmt_isort = "isort ."
fmt_rust = "cargo fmt"
fmt = "task fmt_black & task fmt_isort &task fmt_rust"

lint = "ruff ."

dev = "maturin dev -E dev --manifest-path=ffmpegwithpy-rust/Cargo.toml"

build = "maturin build --release -o dist --manifest-path=ffmpegwithpy-rust/Cargo.toml"
