site_name: ffmpegwithpy
site_url: https://my-mc.github.io/ffmpegwithpy-rust/
theme:
  name: material
  language: en
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

  features:
  - search.suggest
  - search.highlight

nav:
  - ffmpegwithpy: index.md
  - About: about.md

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Japanese
      link: /ja/
      lang: ja

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
