name: lint

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  ruff:
    if: github.event.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.3.1
        with:
          python-version: "3.7"
          cache: "pip"
          cache-dependency-path: "ffmpegwithpy-rust/pyproject.toml"

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: wheels
          workflow: CI

      - name: Install dependencies
        uses: |
          files=(wheels/*linux*)
          pip install "${files[@]}[dev]"

      - name: Run ruff
        run: task lint
