name: lint

on:
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.7"
          cache: "pip"
          cache-dependency-path: "ffmpegwithpy-rust/pyproject.toml"

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff
        run: ruff .
