name: Test

on:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.10'

      - name: Install Dev dependence
        run: |
          python -m pip install --upgrade pip
          pip install maturin
          maturin dev -E dev

      - name: Run pytest
        run: |
          pytest

  cargo:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run unittest
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
